include <ConstantsFile.scad>;

EDGE_SIZE = 100;
FRACTAL_DEPTH = 3;
ORIGIN = 0;
DEFAULT_SIDE_SIZE = 1;
DEFAULT_MAX_SIDES = 1;
DEFAULT_DEPTH_LEVEL = 1;
MENGER_SPONGE_ROTATION = [FORTYFIVE_DEGREES, atan(1/sqrt(2)), ZERO_DEGREES];
NEGATIVE_MENGER_SPONGE_ROTATION = [
												NO_ROTATION,
												[ZERO_DEGREES, ZERO_DEGREES, RIGHT_ANGLE],
												[ZERO_DEGREES, RIGHT_ANGLE, ZERO_DEGREES]
											 ];
LEVEL_GRANULARITY = 1;