CENTERED = true;

ZERO_DEGREES = 0;
RIGHT_ANGLE = 90;
FORTYFIVE_DEGREES = 45;

NO_ROTATION = [ZERO_DEGREES, ZERO_DEGREES, ZERO_DEGREES];

NEGATIVE = -1;
POSITIVE = 1;
SKIP = 0;
BLOCK_RANGE = [NEGATIVE, SKIP, POSITIVE];	
REGULAR_SIDE_SPLIT = 3;
DIMENSION = 1.1;

